baseurl: "" # the subpath of your site, e.g. /blog
url: "https://exothermicrobotics.org" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: /blog/page:num/


plugins: [jekyll-paginate]

